remote_theme: niklasweimann/just-the-docs

# the base hostname & protocol for your site, e.g. http://example.com
url: "https://rxtelegram.github.io"
# the subpath of your site, e.g. /blog
baseurl: "/" 

# Enable or disable the site search
search_enabled: true

markdown: kramdown
heading_anchors: true

relative_links:
  enabled: true

# Aux links for the upper right navigation
aux_links:
  "RxTelegram.Bot on GitHub":
    - "//github.com/rxtelegram/rxtelegram.bot"

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- just-the-docs
- jekyll-remote-theme
- jekyll-relative-links
