version: '3'
services:
    jekyll:
        image: jekyll/jekyll:3.8.3
        environment:
            - JEKYILL_ENV=docker
        command: jekyll serve --host 0.0.0.0 --drafts --config _config.yml --watch --livereload --baseurl "/"
        volumes:
            - .:/srv/jekyll
            - ./vendor/bundle:/usr/local/bundle

        ports:
            - 4000:4000
            - 35729:35729
